services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Gateway for all services
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
